In [1]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [16]:
array1.dtype  # Check the data type of the array

dtype('int64')

In [6]:
array1.ndim  # Check the number of dimensions

1

In [18]:
array1.shape  # This will return the shape of the array

(5,)

In [7]:
array1.size  # Get the size of the array

5

In [ ]:
array1[[1]] # Access element at index 1

array([2])

In [12]:
array1[[1, 3]]  # Access elements at indices 1 and 3

array([2, 4])

In [15]:
array1[[-1]] # Access the last element

array([5])

In [ ]:
array2 = np.array([[1,2,3], [4,5,6]])   # Create a 2D array
print(array2)
array2.ndim

[[1 2 3]
 [4 5 6]]


2

In [19]:
array2.shape  # Get the shape of the 2D array

(2, 3)

In [17]:
array2.reshape(3, 2)  # Reshape the array to 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
array = np.arange(2,11)  # Create an array with even numbers from 2 to 10
print(array2)

[ 2  3  4  5  6  7  8  9 10]


In [28]:
array.reshape(3,3) # Reshape the array to 3 rows and 3 columns

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([[7, 8, 9], [10, 11, 12]])
print(b)
c = a+b  # Element-wise addition
d= a-b  # Element-wise subtraction
e= a/b  # Element-wise division
f= a*b  # Element-wise multiplication
g= a**b # Element-wise exponentiation
print("""---------------------""")
print(c," Element-wise addition")
print(d," Element-wise subtraction")
print(e," Element-wise division")
print(f," Element-wise multiplication")
print(g," Element-wise exponentiation")

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
---------------------
[[ 8 10 12]
 [14 16 18]]  Element-wise addition
[[-6 -6 -6]
 [-6 -6 -6]]  Element-wise subtraction
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]  Element-wise division
[[ 7 16 27]
 [40 55 72]]  Element-wise multiplication
[[         1        256      19683]
 [   1048576   48828125 2176782336]]  Element-wise exponentiation


In [41]:
array1.argmax()  # Find the index of the maximum element in array1
array1.argmin()  # Find the index of the minimum element in array1

np.int64(0)

In [45]:
np.linspace(0, 5 , 5, dtype=int)  # Create an array with 5 evenly spaced numbers between 0 and 5

array([0, 1, 2, 3, 5])

In [52]:
res = np.diff(array1)  # Calculate the difference between consecutive elements
print(res)
res2 = np.diff(array2, axis=0)  # Calculate the difference along the first axis (rows)
print(res2)

[1 1 1 1]
[1 1 1 1 1 1 1 1]
