In [1]:
import numpy as np

In [22]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
zeros_zrr = np.zeros(10)

zeros_zrr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
type(zeros_zrr)

numpy.ndarray

In [21]:
type(zeros_zrr[1])

numpy.float64

In [11]:
zeros_zrr.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr2d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]], dtype=int)
arr2d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr2d.dtype

dtype('int64')

In [55]:
arr2d.ndim

3

In [56]:
arr2d.shape

(1, 4, 3)

In [58]:
np.swapaxes(arr2d, 1, 0)

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [59]:
np.swapaxes(arr2d, 0, 2)

array([[[ 1],
        [ 4],
        [ 7],
        [10]],

       [[ 2],
        [ 5],
        [ 8],
        [11]],

       [[ 3],
        [ 6],
        [ 9],
        [12]]])

In [73]:
np.max(arr2d)

np.int64(12)

In [63]:
arr1.reshape(1,2,5)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [81]:
np.linspace(0, 5 , 5, dtype=int)

array([0, 1, 2, 3, 5])

In [ ]:
arr= ([10, 9 , 8, 7, 6, 5, 4, 3, 2, 1])
np.sort(arr, axis=0 )  # axis=0 sorts along the first axis (rows)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])